# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /opt/local/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/sdw/pic/gitn/k/main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/sdw/pic/gitn/k/main

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /Users/sdw/pic/gitn/k/main && $(CMAKE_COMMAND) -E cmake_progress_start /Users/sdw/pic/gitn/k/main/CMakeFiles /Users/sdw/pic/gitn/k/main/3p/libuc/CMakeFiles/progress.marks
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f CMakeFiles/Makefile2 3p/libuc/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/sdw/pic/gitn/k/main/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f CMakeFiles/Makefile2 3p/libuc/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f CMakeFiles/Makefile2 3p/libuc/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f CMakeFiles/Makefile2 3p/libuc/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/sdw/pic/gitn/k/main && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
3p/libuc/CMakeFiles/UnivCont.dir/rule:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f CMakeFiles/Makefile2 3p/libuc/CMakeFiles/UnivCont.dir/rule
.PHONY : 3p/libuc/CMakeFiles/UnivCont.dir/rule

# Convenience name for target.
UnivCont: 3p/libuc/CMakeFiles/UnivCont.dir/rule
.PHONY : UnivCont

# fast build rule for target.
UnivCont/fast:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/build
.PHONY : UnivCont/fast

buffer.o: buffer.cpp.o
.PHONY : buffer.o

# target to build an object file
buffer.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer.cpp.o
.PHONY : buffer.cpp.o

buffer.i: buffer.cpp.i
.PHONY : buffer.i

# target to preprocess a source file
buffer.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer.cpp.i
.PHONY : buffer.cpp.i

buffer.s: buffer.cpp.s
.PHONY : buffer.s

# target to generate assembly for a file
buffer.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer.cpp.s
.PHONY : buffer.cpp.s

buffer_adapter.o: buffer_adapter.cpp.o
.PHONY : buffer_adapter.o

# target to build an object file
buffer_adapter.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer_adapter.cpp.o
.PHONY : buffer_adapter.cpp.o

buffer_adapter.i: buffer_adapter.cpp.i
.PHONY : buffer_adapter.i

# target to preprocess a source file
buffer_adapter.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer_adapter.cpp.i
.PHONY : buffer_adapter.cpp.i

buffer_adapter.s: buffer_adapter.cpp.s
.PHONY : buffer_adapter.s

# target to generate assembly for a file
buffer_adapter.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer_adapter.cpp.s
.PHONY : buffer_adapter.cpp.s

buffer_util.o: buffer_util.cpp.o
.PHONY : buffer_util.o

# target to build an object file
buffer_util.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer_util.cpp.o
.PHONY : buffer_util.cpp.o

buffer_util.i: buffer_util.cpp.i
.PHONY : buffer_util.i

# target to preprocess a source file
buffer_util.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer_util.cpp.i
.PHONY : buffer_util.cpp.i

buffer_util.s: buffer_util.cpp.s
.PHONY : buffer_util.s

# target to generate assembly for a file
buffer_util.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/buffer_util.cpp.s
.PHONY : buffer_util.cpp.s

string_util.o: string_util.cpp.o
.PHONY : string_util.o

# target to build an object file
string_util.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/string_util.cpp.o
.PHONY : string_util.cpp.o

string_util.i: string_util.cpp.i
.PHONY : string_util.i

# target to preprocess a source file
string_util.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/string_util.cpp.i
.PHONY : string_util.cpp.i

string_util.s: string_util.cpp.s
.PHONY : string_util.s

# target to generate assembly for a file
string_util.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/string_util.cpp.s
.PHONY : string_util.cpp.s

uc_web.o: uc_web.cpp.o
.PHONY : uc_web.o

# target to build an object file
uc_web.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/uc_web.cpp.o
.PHONY : uc_web.cpp.o

uc_web.i: uc_web.cpp.i
.PHONY : uc_web.i

# target to preprocess a source file
uc_web.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/uc_web.cpp.i
.PHONY : uc_web.cpp.i

uc_web.s: uc_web.cpp.s
.PHONY : uc_web.s

# target to generate assembly for a file
uc_web.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/uc_web.cpp.s
.PHONY : uc_web.cpp.s

ucadaptor.o: ucadaptor.cpp.o
.PHONY : ucadaptor.o

# target to build an object file
ucadaptor.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucadaptor.cpp.o
.PHONY : ucadaptor.cpp.o

ucadaptor.i: ucadaptor.cpp.i
.PHONY : ucadaptor.i

# target to preprocess a source file
ucadaptor.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucadaptor.cpp.i
.PHONY : ucadaptor.cpp.i

ucadaptor.s: ucadaptor.cpp.s
.PHONY : ucadaptor.s

# target to generate assembly for a file
ucadaptor.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucadaptor.cpp.s
.PHONY : ucadaptor.cpp.s

ucdb.o: ucdb.cpp.o
.PHONY : ucdb.o

# target to build an object file
ucdb.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucdb.cpp.o
.PHONY : ucdb.cpp.o

ucdb.i: ucdb.cpp.i
.PHONY : ucdb.i

# target to preprocess a source file
ucdb.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucdb.cpp.i
.PHONY : ucdb.cpp.i

ucdb.s: ucdb.cpp.s
.PHONY : ucdb.s

# target to generate assembly for a file
ucdb.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucdb.cpp.s
.PHONY : ucdb.cpp.s

ucio.o: ucio.cpp.o
.PHONY : ucio.o

# target to build an object file
ucio.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucio.cpp.o
.PHONY : ucio.cpp.o

ucio.i: ucio.cpp.i
.PHONY : ucio.i

# target to preprocess a source file
ucio.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucio.cpp.i
.PHONY : ucio.cpp.i

ucio.s: ucio.cpp.s
.PHONY : ucio.s

# target to generate assembly for a file
ucio.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucio.cpp.s
.PHONY : ucio.cpp.s

ucoder_bin.o: ucoder_bin.cpp.o
.PHONY : ucoder_bin.o

# target to build an object file
ucoder_bin.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_bin.cpp.o
.PHONY : ucoder_bin.cpp.o

ucoder_bin.i: ucoder_bin.cpp.i
.PHONY : ucoder_bin.i

# target to preprocess a source file
ucoder_bin.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_bin.cpp.i
.PHONY : ucoder_bin.cpp.i

ucoder_bin.s: ucoder_bin.cpp.s
.PHONY : ucoder_bin.s

# target to generate assembly for a file
ucoder_bin.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_bin.cpp.s
.PHONY : ucoder_bin.cpp.s

ucoder_ini.o: ucoder_ini.cpp.o
.PHONY : ucoder_ini.o

# target to build an object file
ucoder_ini.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_ini.cpp.o
.PHONY : ucoder_ini.cpp.o

ucoder_ini.i: ucoder_ini.cpp.i
.PHONY : ucoder_ini.i

# target to preprocess a source file
ucoder_ini.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_ini.cpp.i
.PHONY : ucoder_ini.cpp.i

ucoder_ini.s: ucoder_ini.cpp.s
.PHONY : ucoder_ini.s

# target to generate assembly for a file
ucoder_ini.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_ini.cpp.s
.PHONY : ucoder_ini.cpp.s

ucoder_json.o: ucoder_json.cpp.o
.PHONY : ucoder_json.o

# target to build an object file
ucoder_json.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_json.cpp.o
.PHONY : ucoder_json.cpp.o

ucoder_json.i: ucoder_json.cpp.i
.PHONY : ucoder_json.i

# target to preprocess a source file
ucoder_json.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_json.cpp.i
.PHONY : ucoder_json.cpp.i

ucoder_json.s: ucoder_json.cpp.s
.PHONY : ucoder_json.s

# target to generate assembly for a file
ucoder_json.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucoder_json.cpp.s
.PHONY : ucoder_json.cpp.s

ucontainer.o: ucontainer.cpp.o
.PHONY : ucontainer.o

# target to build an object file
ucontainer.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucontainer.cpp.o
.PHONY : ucontainer.cpp.o

ucontainer.i: ucontainer.cpp.i
.PHONY : ucontainer.i

# target to preprocess a source file
ucontainer.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucontainer.cpp.i
.PHONY : ucontainer.cpp.i

ucontainer.s: ucontainer.cpp.s
.PHONY : ucontainer.s

# target to generate assembly for a file
ucontainer.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/ucontainer.cpp.s
.PHONY : ucontainer.cpp.s

win32fix.o: win32fix.cpp.o
.PHONY : win32fix.o

# target to build an object file
win32fix.cpp.o:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/win32fix.cpp.o
.PHONY : win32fix.cpp.o

win32fix.i: win32fix.cpp.i
.PHONY : win32fix.i

# target to preprocess a source file
win32fix.cpp.i:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/win32fix.cpp.i
.PHONY : win32fix.cpp.i

win32fix.s: win32fix.cpp.s
.PHONY : win32fix.s

# target to generate assembly for a file
win32fix.cpp.s:
	cd /Users/sdw/pic/gitn/k/main && $(MAKE) -f 3p/libuc/CMakeFiles/UnivCont.dir/build.make 3p/libuc/CMakeFiles/UnivCont.dir/win32fix.cpp.s
.PHONY : win32fix.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... UnivCont"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... buffer.o"
	@echo "... buffer.i"
	@echo "... buffer.s"
	@echo "... buffer_adapter.o"
	@echo "... buffer_adapter.i"
	@echo "... buffer_adapter.s"
	@echo "... buffer_util.o"
	@echo "... buffer_util.i"
	@echo "... buffer_util.s"
	@echo "... string_util.o"
	@echo "... string_util.i"
	@echo "... string_util.s"
	@echo "... uc_web.o"
	@echo "... uc_web.i"
	@echo "... uc_web.s"
	@echo "... ucadaptor.o"
	@echo "... ucadaptor.i"
	@echo "... ucadaptor.s"
	@echo "... ucdb.o"
	@echo "... ucdb.i"
	@echo "... ucdb.s"
	@echo "... ucio.o"
	@echo "... ucio.i"
	@echo "... ucio.s"
	@echo "... ucoder_bin.o"
	@echo "... ucoder_bin.i"
	@echo "... ucoder_bin.s"
	@echo "... ucoder_ini.o"
	@echo "... ucoder_ini.i"
	@echo "... ucoder_ini.s"
	@echo "... ucoder_json.o"
	@echo "... ucoder_json.i"
	@echo "... ucoder_json.s"
	@echo "... ucontainer.o"
	@echo "... ucontainer.i"
	@echo "... ucontainer.s"
	@echo "... win32fix.o"
	@echo "... win32fix.i"
	@echo "... win32fix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/sdw/pic/gitn/k/main && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

